monitor = , preferred, auto, 1

plugin {
    split-monitor-workspaces {
        count = 10                         # Number of workspaces per monitor
        enable_persistent_workspaces = 1
        link_monitors = 0                  # Set to 0 for independent workspaces per monitor
#         monitor_priority = DP-1, DVI-D-1 # Optional: define monitor order
#         max_workspaces = DP-1, 9 # Optional: set max workspaces per specific monitor
    }
}