color0 #111411
color1 #ffb4ab
color2 #81d997
color3 #b7ccb7
color4 #a2ced8
color5 #81d997
color6 #b7ccb7
color7 #e2e3de
color8 #8b938a
color9 #ffb4ab
color10 #81d997
color11 #b7ccb7
color12 #a2ced8
color13 #81d997
color14 #b7ccb7
color15 #e2e3de

cursor                #e2e3de
cursor_text_color     #111411
background            #111411
foreground            #e2e3de
selection_foreground  #c1c9bf
selection_background  #414941
active_border_color   #81d997
inactive_border_color #414941
url_color             #81d997

active_tab_foreground   #003919
active_tab_background   #81d997
inactive_tab_foreground #c1c9bf
inactive_tab_background #414941
cursor_trail_color      #c1c9bf
